import { createHash } from 'node:crypto';
import { canonicalJson } from '../audit/hash-chain';

/**
 * Regulatory-filing export (Phase 15) — pure, deterministic.
 *
 * Assembles a structured ESRS/CSRD-style disclosure document from what the
 * platform already produces: the versioned rule store (requirements → disclosures
 * → required datapoints), the Phase-7 compliance mappings that resolve each
 * required datapoint to a value + trust + evidence, and the Phase-8 audit-chain
 * check. Every figure carries its lineage; a "do not file" guard blocks the
 * filing when required datapoints are missing / unverified or the audit chain
 * does not verify. TRACE never asserts compliance — the document says what was
 * prepared and what gaps remain.
 *
 * `@trace/db/filing.ts` gathers the inputs and content-addresses the output to
 * object storage; `renderFilingHtml` produces a tagged HTML rendering.
 */

export const FILING_FORMAT_VERSION = 'esrs-filing@1.0.0';

export const FILING_DISCLAIMER =
  'This document is a preparation aid generated by TRACE from the organisation’s own ' +
  'data. It is not a compliance opinion and does not assert conformity with any ' +
  'regulation. Figures are reproduced with their lineage; unverified or missing ' +
  'datapoints are listed as gaps. The organisation and its assurance provider remain ' +
  'responsible for any regulatory submission.';

export type FilingDatapointResolution = 'reported' | 'flagged' | 'gap';
export type FilingReadiness = 'ready' | 'blocked';

export interface FilingEvidenceRef {
  id: string;
  type: string;
  title: string;
  status: string;
  hash: string;
}

export interface FilingMappingInput {
  /** ComplianceStatus of the Phase-7 mapping, or null when there is no mapping. */
  status: string | null;
  gapReasons: string[];
  resolvedValue: number | null;
  resolvedValueText: string | null;
  trustScore: number | null;
  confirmed: boolean;
  datapointIds: string[];
  calculationIds: string[];
  evidence: FilingEvidenceRef[];
}

export interface FilingRequiredDatapoint {
  key: string;
  label: string;
  metricKey: string;
  unit: string | null;
  cardinality: string;
  minTrustScore: number | null;
  mapping: FilingMappingInput | null;
}

export interface FilingDisclosure {
  code: string;
  title: string;
  guidance: string;
  status: string;
  requiredDatapoints: FilingRequiredDatapoint[];
  evidenceRequirements: Array<{ key: string; description: string; acceptableTypes: string[] }>;
}

export interface FilingRequirement {
  code: string;
  title: string;
  disclosures: FilingDisclosure[];
}

export interface AssembleFilingInput {
  organization: { legalName: string; country: string; baseCurrency: string };
  regulation: {
    key: string;
    name: string;
    jurisdiction: string;
    ruleStoreVersion: string;
    notice: string;
  };
  reportingPeriod: string;
  requirements: FilingRequirement[];
  auditChainIntact: boolean;
  generatedAt: string;
  generatedBy: string | null;
}

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

const REJECTED_EVIDENCE = new Set(['rejected', 'expired', 'superseded']);

export interface DatapointClassification {
  resolution: FilingDatapointResolution;
  reasons: string[];
}

export function classifyFilingDatapoint(rd: FilingRequiredDatapoint): DatapointClassification {
  const m = rd.mapping;
  if (!m || m.status == null) {
    return { resolution: 'gap', reasons: ['no_mapping'] };
  }
  const hasValue = m.resolvedValue != null || (m.resolvedValueText ?? '').trim().length > 0;
  const trustOk =
    rd.minTrustScore == null || (m.trustScore != null && m.trustScore >= rd.minTrustScore);
  const acceptableEvidence = m.evidence.filter((e) => !REJECTED_EVIDENCE.has(e.status));

  if (!hasValue) {
    return {
      resolution: 'gap',
      reasons: m.gapReasons.length > 0 ? m.gapReasons : ['missing_data'],
    };
  }
  if (!trustOk) {
    return { resolution: 'gap', reasons: ['below_trust'] };
  }
  if (acceptableEvidence.length === 0) {
    return { resolution: 'gap', reasons: ['no_acceptable_evidence'] };
  }
  if (m.status === 'review_required' || !m.confirmed) {
    return { resolution: 'flagged', reasons: ['awaiting_review'] };
  }
  if (m.status === 'mapping_complete') {
    return { resolution: 'reported', reasons: [] };
  }
  return { resolution: 'flagged', reasons: [m.status] };
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

export interface FilingDatapointNode {
  key: string;
  label: string;
  metricKey: string;
  unit: string | null;
  cardinality: string;
  value: number | null;
  valueText: string | null;
  trustScore: number | null;
  minTrustScore: number | null;
  resolution: FilingDatapointResolution;
  reasons: string[];
  datapointIds: string[];
  calculationIds: string[];
  evidence: FilingEvidenceRef[];
}

export interface FilingDisclosureNode {
  code: string;
  title: string;
  guidance: string;
  status: string;
  datapoints: FilingDatapointNode[];
  evidenceRequirements: FilingDisclosure['evidenceRequirements'];
}

export interface FilingRequirementNode {
  code: string;
  title: string;
  disclosures: FilingDisclosureNode[];
}

export interface FilingGap {
  requirementCode: string;
  disclosureCode: string;
  datapointKey: string;
  label: string;
  reasons: string[];
}

export interface FilingStats {
  requiredDatapoints: number;
  reported: number;
  flagged: number;
  gaps: number;
  evidenceItems: number;
  disclosures: number;
  disclosuresComplete: number;
}

export interface RegulatoryFiling {
  formatVersion: string;
  organization: AssembleFilingInput['organization'];
  regulation: AssembleFilingInput['regulation'];
  reportingPeriod: string;
  generatedAt: string;
  generatedBy: string | null;
  readiness: FilingReadiness;
  blockers: string[];
  stats: FilingStats;
  sections: FilingRequirementNode[];
  gaps: FilingGap[];
  auditChainIntact: boolean;
  disclaimer: string;
  notice: string;
  digest: string;
}

export function assembleFiling(input: AssembleFilingInput): RegulatoryFiling {
  const gaps: FilingGap[] = [];
  let reported = 0;
  let flagged = 0;
  let gapCount = 0;
  let requiredCount = 0;
  let evidenceItems = 0;
  let disclosures = 0;
  let disclosuresComplete = 0;

  const sections: FilingRequirementNode[] = input.requirements.map((req) => ({
    code: req.code,
    title: req.title,
    disclosures: req.disclosures.map((dis) => {
      disclosures += 1;
      let disHasGap = false;
      const datapoints: FilingDatapointNode[] = dis.requiredDatapoints.map((rd) => {
        requiredCount += 1;
        const { resolution, reasons } = classifyFilingDatapoint(rd);
        if (resolution === 'reported') reported += 1;
        else if (resolution === 'flagged') flagged += 1;
        else gapCount += 1;
        if (resolution !== 'reported') disHasGap = true;
        if (resolution === 'gap') {
          gaps.push({
            requirementCode: req.code,
            disclosureCode: dis.code,
            datapointKey: rd.key,
            label: rd.label,
            reasons,
          });
        }
        const ev = rd.mapping?.evidence ?? [];
        evidenceItems += ev.length;
        return {
          key: rd.key,
          label: rd.label,
          metricKey: rd.metricKey,
          unit: rd.unit,
          cardinality: rd.cardinality,
          value: rd.mapping?.resolvedValue ?? null,
          valueText: rd.mapping?.resolvedValueText ?? null,
          trustScore: rd.mapping?.trustScore ?? null,
          minTrustScore: rd.minTrustScore,
          resolution,
          reasons,
          datapointIds: rd.mapping?.datapointIds ?? [],
          calculationIds: rd.mapping?.calculationIds ?? [],
          evidence: ev,
        };
      });
      if (!disHasGap && datapoints.length > 0) disclosuresComplete += 1;
      return {
        code: dis.code,
        title: dis.title,
        guidance: dis.guidance,
        status: dis.status,
        datapoints,
        evidenceRequirements: dis.evidenceRequirements,
      };
    }),
  }));

  const blockers: string[] = [];
  if (!input.auditChainIntact) blockers.push('The audit-log chain does not verify.');
  for (const g of gaps) {
    blockers.push(`${g.disclosureCode} / ${g.datapointKey}: ${g.reasons.join(', ')}`);
  }
  if (flagged > 0 && gaps.length === 0) {
    blockers.push(`${flagged} datapoint(s) resolved but awaiting human review.`);
  }
  const readiness: FilingReadiness =
    gaps.length === 0 && flagged === 0 && input.auditChainIntact ? 'ready' : 'blocked';

  const stats: FilingStats = {
    requiredDatapoints: requiredCount,
    reported,
    flagged,
    gaps: gapCount,
    evidenceItems,
    disclosures,
    disclosuresComplete,
  };

  const body = {
    formatVersion: FILING_FORMAT_VERSION,
    organization: input.organization,
    regulation: input.regulation,
    reportingPeriod: input.reportingPeriod,
    generatedAt: input.generatedAt,
    generatedBy: input.generatedBy,
    readiness,
    blockers,
    stats,
    sections,
    gaps,
    auditChainIntact: input.auditChainIntact,
    disclaimer: FILING_DISCLAIMER,
    notice: input.regulation.notice,
  };
  const digest = createHash('sha256').update(canonicalJson(body)).digest('hex');

  return { ...body, digest };
}

// ---------------------------------------------------------------------------
// Tagged HTML rendering
// ---------------------------------------------------------------------------

function esc(v: unknown): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function renderFilingHtml(filing: RegulatoryFiling): string {
  const p: string[] = [];
  p.push('<!doctype html><html lang="en"><head><meta charset="utf-8">');
  p.push(`<title>${esc(filing.regulation.name)} — ${esc(filing.reportingPeriod)}</title>`);
  p.push('</head><body>');
  p.push(
    `<article data-esrs-filing data-format="${esc(filing.formatVersion)}" ` +
      `data-regulation="${esc(filing.regulation.key)}" ` +
      `data-rule-store="${esc(filing.regulation.ruleStoreVersion)}" ` +
      `data-period="${esc(filing.reportingPeriod)}" ` +
      `data-readiness="${esc(filing.readiness)}">`,
  );

  p.push('<header data-filing-header>');
  p.push(`<h1>${esc(filing.regulation.name)}</h1>`);
  p.push(
    `<p data-org data-country="${esc(filing.organization.country)}" ` +
      `data-currency="${esc(filing.organization.baseCurrency)}">` +
      `${esc(filing.organization.legalName)} — ${esc(filing.reportingPeriod)}</p>`,
  );
  p.push(
    `<p data-stats>Required datapoints: ${filing.stats.requiredDatapoints} · ` +
      `reported ${filing.stats.reported} · flagged ${filing.stats.flagged} · ` +
      `gaps ${filing.stats.gaps} · evidence items ${filing.stats.evidenceItems} · ` +
      `disclosures complete ${filing.stats.disclosuresComplete}/${filing.stats.disclosures}</p>`,
  );
  p.push(
    `<p data-audit-chain="${filing.auditChainIntact ? 'intact' : 'broken'}">` +
      `Audit-log chain: ${filing.auditChainIntact ? 'verified' : 'NOT verified'}</p>`,
  );
  p.push('</header>');

  for (const req of filing.sections) {
    p.push(`<section data-requirement="${esc(req.code)}"><h2>${esc(req.code)} — ${esc(req.title)}</h2>`);
    for (const dis of req.disclosures) {
      p.push(
        `<section data-disclosure="${esc(dis.code)}" data-status="${esc(dis.status)}">` +
          `<h3>${esc(dis.code)} — ${esc(dis.title)}</h3>`,
      );
      if (dis.guidance) p.push(`<p data-guidance>${esc(dis.guidance)}</p>`);
      for (const dp of dis.datapoints) {
        p.push(
          `<div data-datapoint="${esc(dp.key)}" data-metric="${esc(dp.metricKey)}" ` +
            `data-unit="${esc(dp.unit ?? '')}" data-cardinality="${esc(dp.cardinality)}" ` +
            `data-trust="${dp.trustScore ?? ''}" data-min-trust="${dp.minTrustScore ?? ''}" ` +
            `data-resolution="${esc(dp.resolution)}" ` +
            `data-value="${esc(dp.value ?? dp.valueText ?? '')}">`,
        );
        const shown =
          dp.value != null
            ? `${dp.value}${dp.unit ? ` ${esc(dp.unit)}` : ''}`
            : dp.valueText
              ? esc(dp.valueText)
              : '— not reported —';
        p.push(
          `<p>${esc(dp.label)}: <strong>${shown}</strong>` +
            (dp.trustScore != null ? ` <span data-trust-badge>trust ${dp.trustScore}</span>` : '') +
            (dp.resolution !== 'reported'
              ? ` <span data-flag>${esc(dp.resolution)}: ${esc(dp.reasons.join(', '))}</span>`
              : '') +
            '</p>',
        );
        if (dp.evidence.length > 0) {
          p.push('<ul data-evidence>');
          for (const e of dp.evidence) {
            p.push(
              `<li data-evidence-id="${esc(e.id)}" data-evidence-type="${esc(e.type)}" ` +
                `data-evidence-status="${esc(e.status)}" data-evidence-hash="${esc(e.hash)}">` +
                `${esc(e.title)} (${esc(e.type)}, ${esc(e.status)})</li>`,
            );
          }
          p.push('</ul>');
        }
        if (dp.datapointIds.length > 0 || dp.calculationIds.length > 0) {
          p.push(
            `<p data-lineage data-datapoint-ids="${esc(dp.datapointIds.join(' '))}" ` +
              `data-calculation-ids="${esc(dp.calculationIds.join(' '))}">lineage on file</p>`,
          );
        }
        p.push('</div>');
      }
      p.push('</section>');
    }
    p.push('</section>');
  }

  if (filing.gaps.length > 0) {
    p.push('<section data-gaps><h2>Outstanding gaps</h2><ul>');
    for (const g of filing.gaps) {
      p.push(
        `<li data-gap data-disclosure="${esc(g.disclosureCode)}" data-datapoint="${esc(g.datapointKey)}">` +
          `${esc(g.disclosureCode)} — ${esc(g.label)}: ${esc(g.reasons.join(', '))}</li>`,
      );
    }
    p.push('</ul></section>');
  }

  if (filing.blockers.length > 0) {
    p.push('<section data-blockers><h2>Filing is blocked</h2><ul>');
    for (const b of filing.blockers) p.push(`<li>${esc(b)}</li>`);
    p.push('</ul></section>');
  }

  if (filing.notice) p.push(`<section data-notice><p>${esc(filing.notice)}</p></section>`);
  p.push(`<footer data-disclaimer><p>${esc(filing.disclaimer)}</p></footer>`);
  p.push(`<!-- digest ${esc(filing.digest)} -->`);
  p.push('</article></body></html>');
  return p.join('\n');
}
